services:
  migrate:
    image: ghcr.io/smith-106/bilibili-electronic-pet:latest
    pull_policy: always
    command: npm run prisma:migrate:prod

  api:
    image: ghcr.io/smith-106/bilibili-electronic-pet:latest
    pull_policy: always
    command: node dist/index.js

  worker:
    image: ghcr.io/smith-106/bilibili-electronic-pet:latest
    pull_policy: always
    command: node dist/workers/worker-main.js
